[package]
name = "order_book_prog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ringbuf = "0.2.7"
core_affinity = "0.5.10"
avl = "0.6.2"